name: ucp_dart
description: Universal Communication Protocol (UCP) for real-time MQTT-based device communication in Dart.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  mqtt_client: ^10.0.0
  mockito: ^5.4.5
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
